apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: demo-ns
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: votingappacr1.azurecr.io/resultapp:v1
        ports:
        - containerPort: 80
          name: result
     
