apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: demo-ns
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: votingappacr1.azurecr.io/workerapp:v1   # <-- ✔ Correct tag
        env:
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: REDIS
          value: redis
     
