name: Voting App CI/CD

on:
  push:
    branches:
      - votingapp
    paths:
      - "vote/**"
      - ".github/workflows/gitpipeline.yaml"

jobs:

  build_push_acr:
    name: Build & Push to ACR
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.setimage.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR
      - name: ACR Login
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Docker Build & Push (v2)
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="${{ secrets.ACR_NAME }}.azurecr.io/votingapp:v2"
          docker build -t $IMAGE_NAME ./vote
          docker push $IMAGE_NAME

      - name: Set output image
        id: setimage
        run: |
          echo "image=${{ secrets.ACR_NAME }}.azurecr.io/votingapp:v2" >> $GITHUB_OUTPUT


  deploy_to_aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build_push_acr

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RG }} \
            --name ${{ secrets.AKS_NAME }} \
            --overwrite-existing

      - name: Apply manifests
        run: |
          kubectl apply -f k8s-specifications/vote-deployment.yaml
          kubectl apply -f k8s-specifications/vote-service.yaml
          
      # Use v2 here also
      - name: Update Kubernetes image
        run: |
          kubectl set image -n demo-ns deployment/vote \
            vote=${{ secrets.ACR_NAME }}.azurecr.io/votingapp:v2

     
